In [1]:
import sys
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
current_path=os.getcwd()
loader_path=os.path.abspath(
    os.path.join(current_path, '..', 'disease_prediction','data',
        )
    )
sys.path.append(loader_path)

In [3]:
import datasets as ds

In [4]:
df=ds.load_datasets(
    subsets=['train', 'test', 'validate'],
    directory='../ddx-dataset/'
)

In [5]:
dp_data=pd.concat(
    [df['train'],df['test'],df['validate']],
    axis=0, 
    ignore_index=True
    )

In [6]:
dp_data.head()

AGE SEX                PATHOLOGY    INITIAL_EVIDENCE  swollen_nodes  std  \
0   21   M  HIV (initial infection)            sweating              0    0   
1    8   M       Allergic sinusitis          itchy_nose              0    0   
2   49   F              Anaphylaxis  lost_consciousness              0    0   
3   69   M             Tuberculosis               cough              0    0   
4   30   F             Tuberculosis         cough_blood              0    0   

   sweating  diarrhea  pain pain_char  ... ca_blockers  vag_discharge  \
0         0         0     0        NA  ...           0              0   
1         0         0     1     heavy  ...           0              0   
2         0         0     0        NA  ...           0              0   
3         0         0     1     heavy  ...           0              0   
4         0         0     1     sharp  ...           0              0   

  wheezing_inhale  fatigue  menarche_12  breastfed_9  confusion  contact  \
0               0        0            0            0          0        0   
1               0        0            0            0          0        0   
2               0        0            0            0          0        0   
3               0        0            0            0          0        0   
4               0        0            0            0          0        0   

  ebolacase bruising  
0         0        0  
1         0        0  
2         0        0  
3         0        0  
4         0        0  

[5 rows x 94 columns]

In [7]:
dp_data.info()

<class 'datasets.DiagDataFrame'>
RangeIndex: 254096 entries, 0 to 254095
Data columns (total 94 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   AGE                     254096 non-null  int64 
 1   SEX                     254096 non-null  object
 2   PATHOLOGY               254096 non-null  object
 3   INITIAL_EVIDENCE        254096 non-null  object
 4   swollen_nodes           254096 non-null  int64 
 5   std                     254096 non-null  int64 
 6   sweating                254096 non-null  int64 
 7   diarrhea                254096 non-null  int64 
 8   pain                    254096 non-null  int64 
 9   pain_char               254096 non-null  object
 10  pain_somewhere          254096 non-null  object
 11  pain_intensity          254096 non-null  int64 
 12  pain_radiate            254096 non-null  object
 13  pain_precise            254096 non-null  int64 
 14  pain_sudden             254096 non-null  

In [8]:
dp_data.describe(include='all')

AGE     SEX                PATHOLOGY INITIAL_EVIDENCE  \
count   254096.000000  254096                   254096           254096   
unique            NaN       2                       11               38   
top               NaN       F  HIV (initial infection)             pain   
freq              NaN  131302                    36784            41872   
mean        37.773259     NaN                      NaN              NaN   
std         23.392348     NaN                      NaN              NaN   
min          0.000000     NaN                      NaN              NaN   
25%         19.000000     NaN                      NaN              NaN   
50%         36.000000     NaN                      NaN              NaN   
75%         55.000000     NaN                      NaN              NaN   
max        109.000000     NaN                      NaN              NaN   

        swollen_nodes            std       sweating       diarrhea  \
count   254096.000000  254096.000000  254096.000000  254096.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean         0.042181       0.021268       0.036427       0.040142   
std          0.201002       0.144275       0.187351       0.196293   
min          0.000000       0.000000       0.000000       0.000000   
25%          0.000000       0.000000       0.000000       0.000000   
50%          0.000000       0.000000       0.000000       0.000000   
75%          0.000000       0.000000       0.000000       0.000000   
max          1.000000       1.000000       1.000000       1.000000   

                 pain pain_char  ...    ca_blockers  vag_discharge  \
count   254096.000000    254096  ...  254096.000000  254096.000000   
unique            NaN        11  ...            NaN            NaN   
top               NaN        NA  ...            NaN            NaN   
freq              NaN    214730  ...            NaN            NaN   
mean         0.154926       NaN  ...       0.016809       0.009516   
std          0.361835       NaN  ...       0.128554       0.097085   
min          0.000000       NaN  ...       0.000000       0.000000   
25%          0.000000       NaN  ...       0.000000       0.000000   
50%          0.000000       NaN  ...       0.000000       0.000000   
75%          0.000000       NaN  ...       0.000000       0.000000   
max          1.000000       NaN  ...       1.000000       1.000000   

       wheezing_inhale        fatigue    menarche_12    breastfed_9  \
count    254096.000000  254096.000000  254096.000000  254096.000000   
unique             NaN            NaN            NaN            NaN   
top                NaN            NaN            NaN            NaN   
freq               NaN            NaN            NaN            NaN   
mean          0.003274       0.007348       0.004164       0.001212   
std           0.057128       0.085403       0.064393       0.034795   
min           0.000000       0.000000       0.000000       0.000000   
25%           0.000000       0.000000       0.000000       0.000000   
50%           0.000000       0.000000       0.000000       0.000000   
75%           0.000000       0.000000       0.000000       0.000000   
max           1.000000       1.000000       1.000000       1.000000   

            confusion        contact      ebolacase       bruising  
count   254096.000000  254096.000000  254096.000000  254096.000000  
unique            NaN            NaN            NaN            NaN  
top               NaN            NaN            NaN            NaN  
freq              NaN            NaN            NaN            NaN  
mean         0.000531       0.000606       0.000724       0.000697  
std          0.023044       0.024611       0.026900       0.026384  
min          0.000000       0.000000       0.000000       0.000000  
25%          0.000000       0.

In [9]:
dp_data.dtypes.unique()

array([dtype('int64'), dtype('O')], dtype=object)

In [10]:
for col in dp_data.columns:
    print(f"Column: {col}")
    print(f"Type: {dp_data[col].dtype}")
    print(f"First 5 values:\n{dp_data[col].head()}\n")

Column: AGE
Type: int64
First 5 values:
0    21
1     8
2    49
3    69
4    30
Name: AGE, dtype: int64

Column: SEX
Type: object
First 5 values:
0    M
1    M
2    F
3    M
4    F
Name: SEX, dtype: object

Column: PATHOLOGY
Type: object
First 5 values:
0    HIV (initial infection)
1         Allergic sinusitis
2                Anaphylaxis
3               Tuberculosis
4               Tuberculosis
Name: PATHOLOGY, dtype: object

Column: INITIAL_EVIDENCE
Type: object
First 5 values:
0              sweating
1            itchy_nose
2    lost_consciousness
3                 cough
4           cough_blood
Name: INITIAL_EVIDENCE, dtype: object

Column: swollen_nodes
Type: int64
First 5 values:
0    0
1    0
2    0
3    0
4    0
Name: swollen_nodes, dtype: int64

Column: std
Type: int64
First 5 values:
0    0
1    0
2    0
3    0
4    0
Name: std, dtype: int64

Column: sweating
Type: int64
First 5 values:
0    0
1    0
2    0
3    0
4    0
Name: sweating, dtype: int64

Column: diarrhea
Type: int

In [11]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, make_scorer

In [12]:
X=dp_data.drop('PATHOLOGY', axis=1)
y=dp_data['PATHOLOGY']

In [13]:
label_encoder=LabelEncoder()
y_encoded=label_encoder.fit_transform(y)

In [14]:
numerical_features=X.select_dtypes(include='int64').columns.tolist()
categorical_features=X.select_dtypes(include='object').columns.tolist()

In [15]:
features_preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),numerical_features),
        ('cat',OneHotEncoder(),categorical_features)
    ]
)

In [16]:
model1=Pipeline(
    steps=[
        ('Pre-processing',features_preprocessor),
        ('classification',RandomForestClassifier(random_state=42))
    ]
)

In [17]:
kf=KFold(n_splits=5, shuffle=True, random_state=42)

In [18]:
def model1_classification_report(y_true,y_pred):
    report=classification_report(
        y_true,y_pred,target_names=label_encoder.classes_,output_dict=True
        )
    return report['accuracy']

In [19]:
model1_scorer=make_scorer(model1_classification_report)

In [20]:
CrossValidation_results=cross_val_score(
    model1,X,y_encoded,cv=kf,scoring='accuracy'
    )

/Users/macpc/Library/CloudStorage/OneDrive-FloridaStateUniversity/OnlineLearning/ErdosInstitute/data_science_bc/disease_prediction/project_env/dp-env/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/macpc/Library/CloudStorage/OneDrive-FloridaStateUniversity/OnlineLearning/ErdosInstitute/data_science_bc/disease_prediction/project_env/dp-env/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/Users/macpc/Library/CloudStorage/OneDrive-FloridaStateUniversity/OnlineLearning/ErdosInstitute/data_science_bc/disease_prediction/project_env/dp-env/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/Users/macpc/Library/CloudStor

In [21]:
print(f"Cross-Validation Accuracy Scores: {CrossValidation_results}")
print(f"Mean Accuracy: {CrossValidation_results.mean()}")
print(f"Standard Deviation: {CrossValidation_results.std()}")

Cross-Validation Accuracy Scores: [       nan        nan 0.58975974 0.59306559        nan]
Mean Accuracy: nan
Standard Deviation: nan


In [22]:
model1.fit(X,y_encoded)
y_pred=model1.predict(X)

In [23]:
# Evaluate the final model
accuracy = accuracy_score(y_encoded, y_pred)
conf_matrix = confusion_matrix(y_encoded, y_pred)
class_report = classification_report(y_encoded, y_pred, target_names=label_encoder.classes_)

print(f"\nFinal Model Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)


Final Model Accuracy: 0.6950561992317864
Confusion Matrix:
[[27783     0     0     0     0    44     0     0     0  2923     0]
 [    0 21645    60     1  3534   240  7424   457  1600   310     0]
 [    0   837  4562     2  1855   294  1858    57  1536   452     0]
 [   13    53     0   356   205    62     0    63    66    90     0]
 [    0  2719    54     0 21154  4725  3879   380  2187  1686     0]
 [ 2774  1021     2     0  6316 17334  3484   346    10  2669     0]
 [    0    15     0     0     2     9 35202     7    18     0     0]
 [    0  1095     3     0  1352   226  3309  7090  1607   328     0]
 [    0    70    13     0   447     6  6096   141 19996   446     0]
 [  908    66     6     0  2401   663     0   108  1855 14325     0]
 [    0     0     0     0     0     0     0     0     0     0  7164]]
Classification Report:
                         precision    recall  f1-score   support

     Allergic sinusitis       0.88      0.90      0.89     30750
            Anaphylaxis   